[project]
name = "katago-train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AAA-huan", email = "2767151990@qq.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "onnx>=1.23.0",
    "onnxscript>=0.7.2",
    "torch>=2.14.0",
]

[project.scripts]
katago-train = "katago_train:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
